create table public.inventory_records (
    id bigint generated by default as identity primary key,
    serial text not null unique,
    weapon_name text not null,
    category text not null default 'Cat 1',
    info_label text not null default 'Aucun fichier',
    info_content text not null default '',
    updated_at timestamptz not null default now()
);

alter table public.inventory_records enable row level security;

drop policy if exists "Public can read inventory" on public.inventory_records;
create policy "Public can read inventory"
on public.inventory_records for select
to anon
using (true);

drop policy if exists "Public can insert inventory" on public.inventory_records;
create policy "Public can insert inventory"
on public.inventory_records for insert
to anon
with check (true);

drop policy if exists "Public can delete inventory" on public.inventory_records;
create policy "Public can delete inventory"
on public.inventory_records for delete
to anon
using (true);

grant select, insert, delete on public.inventory_records to anon;
grant usage, select on sequence public.inventory_records_id_seq to anon;
