create table public.inventory_records (
    id bigint generated by default as identity primary key,
    serial text not null unique,
    weapon_name text not null,
    category text not null default 'Cat 1',
    info_label text not null default 'Aucun fichier',
    info_content text not null default '',
    updated_at timestamptz not null default now()
);

alter table public.inventory_records enable row level security;

create policy "Public can read inventory"
on public.inventory_records for select
using (true);

create or replace function public.replace_inventory(p_rows jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    delete from public.inventory_records;

    insert into public.inventory_records (serial, weapon_name, category, info_label, info_content, updated_at)
    select serial, weapon_name, category, info_label, info_content, now()
    from jsonb_to_recordset(p_rows) as records(
        serial text,
        weapon_name text,
        category text,
        info_label text,
        info_content text
    );
end;
$$;

grant execute on function public.replace_inventory(jsonb) to anon;
